version: '3.7'
services:
    database:
        image: 'mysql:latest'
        volumes:
            -   ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: analizujtypy
        ports:
            - '3306:3306'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        links:
            - database
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
        restart: always