<?php

namespace ContainerPnGOIwr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HWALy44Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hWALy44' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hWALy44'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chartBuilder' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
            'chartService' => ['privates', 'App\\Service\\ChartService', 'getChartServiceService', true],
            'computerLogContainer' => ['privates', 'App\\Service\\ComputerLogContainer', 'getComputerLogContainerService', true],
            'computerLogService' => ['privates', 'App\\Service\\ComputerLogService', 'getComputerLogServiceService', true],
        ], [
            'chartBuilder' => '?',
            'chartService' => 'App\\Service\\ChartService',
            'computerLogContainer' => 'App\\Service\\ComputerLogContainer',
            'computerLogService' => 'App\\Service\\ComputerLogService',
        ]);
    }
}
