<?php

namespace ContainerPnGOIwr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E2rsqEoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E2rsqEo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E2rsqEo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projectsService' => ['privates', 'App\\Service\\ProjectsService', 'getProjectsServiceService', true],
        ], [
            'projectsService' => 'App\\Service\\ProjectsService',
        ]);
    }
}
