<?php

namespace ContainerPnGOIwr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OhZwzCaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ohZwzCa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ohZwzCa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'usersService' => ['privates', 'App\\Service\\UsersService', 'getUsersServiceService', true],
        ], [
            'usersService' => 'App\\Service\\UsersService',
        ]);
    }
}
