<?php

namespace ContainerPnGOIwr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\UsersService' shared autowired service.
     *
     * @return \App\Service\UsersService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UsersService.php';

        return $container->privates['App\\Service\\UsersService'] = new \App\Service\UsersService(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
