<?php

namespace ContainerFHRep1H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9XoJcQ2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9XoJcQ2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9XoJcQ2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::chart' => ['privates', '.service_locator.4TftXj6', 'get_ServiceLocator_4TftXj6Service', true],
            'App\\Controller\\AdminController::users' => ['privates', '.service_locator.ohZwzCa', 'get_ServiceLocator_OhZwzCaService', true],
            'App\\Controller\\AdminController::users_assign_roles' => ['privates', '.service_locator.ohZwzCa', 'get_ServiceLocator_OhZwzCaService', true],
            'App\\Controller\\DisplayComputerLogController::index' => ['privates', '.service_locator.hWALy44', 'get_ServiceLocator_HWALy44Service', true],
            'App\\Controller\\ProjectsController::editProject' => ['privates', '.service_locator.E2rsqEo', 'get_ServiceLocator_E2rsqEoService', true],
            'App\\Controller\\ProjectsController::index' => ['privates', '.service_locator.E2rsqEo', 'get_ServiceLocator_E2rsqEoService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.spC.Z_T', 'get_ServiceLocator_SpC_ZTService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\AdminController:chart' => ['privates', '.service_locator.4TftXj6', 'get_ServiceLocator_4TftXj6Service', true],
            'App\\Controller\\AdminController:users' => ['privates', '.service_locator.ohZwzCa', 'get_ServiceLocator_OhZwzCaService', true],
            'App\\Controller\\AdminController:users_assign_roles' => ['privates', '.service_locator.ohZwzCa', 'get_ServiceLocator_OhZwzCaService', true],
            'App\\Controller\\DisplayComputerLogController:index' => ['privates', '.service_locator.hWALy44', 'get_ServiceLocator_HWALy44Service', true],
            'App\\Controller\\ProjectsController:editProject' => ['privates', '.service_locator.E2rsqEo', 'get_ServiceLocator_E2rsqEoService', true],
            'App\\Controller\\ProjectsController:index' => ['privates', '.service_locator.E2rsqEo', 'get_ServiceLocator_E2rsqEoService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.spC.Z_T', 'get_ServiceLocator_SpC_ZTService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\AdminController::chart' => '?',
            'App\\Controller\\AdminController::users' => '?',
            'App\\Controller\\AdminController::users_assign_roles' => '?',
            'App\\Controller\\DisplayComputerLogController::index' => '?',
            'App\\Controller\\ProjectsController::editProject' => '?',
            'App\\Controller\\ProjectsController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:chart' => '?',
            'App\\Controller\\AdminController:users' => '?',
            'App\\Controller\\AdminController:users_assign_roles' => '?',
            'App\\Controller\\DisplayComputerLogController:index' => '?',
            'App\\Controller\\ProjectsController:editProject' => '?',
            'App\\Controller\\ProjectsController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
