<?php

namespace ContainerFHRep1H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComputerLogServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ComputerLogService' shared autowired service.
     *
     * @return \App\Service\ComputerLogService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ComputerLogService.php';

        return $container->privates['App\\Service\\ComputerLogService'] = new \App\Service\ComputerLogService(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()));
    }
}
