<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNuXHFS5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNuXHFS5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNuXHFS5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNuXHFS5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNuXHFS5\App_KernelDevDebugContainer([
    'container.build_hash' => 'NuXHFS5',
    'container.build_id' => '04d60675',
    'container.build_time' => 1671733366,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNuXHFS5');
