<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPnGOIwr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPnGOIwr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPnGOIwr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPnGOIwr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPnGOIwr\App_KernelDevDebugContainer([
    'container.build_hash' => 'PnGOIwr',
    'container.build_id' => '564faa4b',
    'container.build_time' => 1665256307,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPnGOIwr');
