<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ExnDNj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ExnDNj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5ExnDNj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5ExnDNj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5ExnDNj\App_KernelDevDebugContainer([
    'container.build_hash' => '5ExnDNj',
    'container.build_id' => 'd16984ad',
    'container.build_time' => 1671818147,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ExnDNj');
