<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.61b1725c.js',
                '/build/222.c27df430.js',
                '/build/524.eb17f2c9.js',
                '/build/app.9372b3d0.js',
            ],
            'css' => [
                '/build/app.873633eb.css',
            ],
        ],
        'app_collection' => [
            'js' => [
                '/build/runtime.61b1725c.js',
                '/build/222.c27df430.js',
                '/build/app_collection.a889aae3.js',
            ],
        ],
    ],
],

]];
